# Generated by Django 4.2.17 on 2025-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image_path', models.CharField(max_length=255, verbose_name='Изображение')),
            ],
        ),
    ]
