# Generated by Django 5.2 on 2025-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        )
    ]
