# Generated by Django 5.2 on 2025-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_rename_categories_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Ключевые слова"
            ),
        ),
    ]
