# Generated by Django 5.2 on 2025-11-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_product_options_product_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descriptions",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Ключевые слова"
            ),
        ),
    ]
