# Generated by Django 5.2 on 2025-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_product_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="descriptions",
            field=models.CharField(null=True, verbose_name="Описание"),
        ),
    ]
