# Generated by Django 5.2 on 2025-11-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_product_descriptions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descriptions",
            new_name="description",
        ),
    ]
